config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  resources :basket_items
  resources :items
  resources :basket
  post '/add_to_basket', to: 'basket#add_to_basket', as: 'add_item'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  has_many :basket_items, dependent: :destroy
end

app/models/basket_item.rb
class BasketItem < ApplicationRecord
  belongs_to :item
  belongs_to :basket
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :basket_items

  before_destroy :there_is_a_item?

  validates :title, :description, :image_url, presence: true
  validates :price,numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\z}i,
    message: 'Не правильный формат изображения'
  }
  private

  def there_is_a_item?
    if basket_items.empty?
      return true
    else
      errors.add(:base, "товарные позиции есть")
      return false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/basket_controller.rb
class BasketController < ApplicationController
  before_action :set_basket, only: [:index, :add_to_basket, :destroy]
  before_action :check_for_basket_limit, only: [:add_to_basket]
  after_action :set_total_price, only: [:add_to_basket, :destroy]
  after_action :add_free_delivery, only: [:add_to_basket, :destroy]

  def index
    @items = @basket.basket_items

  end

  def add_to_basket
    item = Item.find(params[:item_id])
    @basket_item = @basket.basket_items.new(item_id: params[:item_id])
    if @basket_item.save
      redirect_to basket_index_path
    else
      redirect_to items_path
      flash[:errors] = 'Basket item was successfully created.'
    end
    # basket.add_item(item)
  end

  def destroy
    basket_item = BasketItem.find(params[:id])
    if basket_item.destroy
      redirect_to basket_index_path
    end
  end



  private

    def set_basket
      @basket = Basket.find(session[:basket_id])
    rescue ActiveRecord::RecordNotFound
      @basket = Basket.create
      session[:basket_id] = @basket.id
    end

    def set_total_price
      total = 0
      items = @basket.basket_items
      items.each do |basket_item|
        total += basket_item.item.price
      end
      session[:basket_total] = total
    end

    def add_free_delivery
      total = session[:basket_total].to_i
      if total >= 3000
        flash[:alert] = 'Бесплатная доставка'
      else
        session[:basket_total].to_i += 300
      end
    end

    def check_for_basket_limit
      if @basket.basket_items.count >= 10
        redirect_to items_path
        flash[:alert] = 'Слишком много товаров'
      end
    end


    def basket_item_params
      params.require(:basket).permit(:item_id)
    end
end

app/controllers/basket_items_controller.rb
class BasketItemsController < ApplicationController
  before_action :set_basket_item, only: [:show, :edit, :update, :destroy]

  # GET /basket_items
  # GET /basket_items.json
  def index
    @basket_items = BasketItem.all
  end

  # GET /basket_items/1
  # GET /basket_items/1.json
  def show
  end

  # GET /basket_items/new
  def new
    @basket_item = BasketItem.new
  end

  # GET /basket_items/1/edit
  def edit
  end

  # POST /basket_items
  # POST /basket_items.json
  def create
    @basket_item = BasketItem.new(basket_item_params)


    respond_to do |format|
      if @basket_item.save
        format.html { redirect_to @basket_item, notice: 'Basket item was successfully created.' }
        format.json { render :show, status: :created, location: @basket_item }
      else
        format.html { render :new }
        format.json { render json: @basket_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /basket_items/1
  # PATCH/PUT /basket_items/1.json
  def update
    respond_to do |format|
      if @basket_item.update(basket_item_params)
        format.html { redirect_to @basket_item, notice: 'Basket item was successfully updated.' }
        format.json { render :show, status: :ok, location: @basket_item }
      else
        format.html { render :edit }
        format.json { render json: @basket_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /basket_items/1
  # DELETE /basket_items/1.json
  def destroy
    @basket_item.destroy
    respond_to do |format|
      format.html { redirect_to basket_items_url, notice: 'Basket item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_basket_item
      @basket_item = BasketItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def basket_item_params
      params.require(:basket_item).permit(:item_id, :basket_id)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.order(:item)
    @items = Item.all

  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :image_url, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basket_helper.rb
module BasketHelper
end

app/helpers/basket_items_helper.rb
module BasketItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/basket/index.html.erb
<div class="basket">
  <h1>Моя корзина</h1>
  <h3>Количество товаров в корзине: <%= @items.count %></h3>
  <h3>
    Общая сумма с учетом доставки: <%= session[:basket_total]%>
    (<%= session[:basket_total].to_i >= 3000 ? " Доставка бесплатная" : "Доставка 300$"%>)
  </h3>
  <p>*Стоимость доставки свыше 3000$ бесплатная</p>
  <div class="basket__list">
    <% @items.each do |basket_item| %>
      <div class="col-sm-4">
        <div class="basket__item ">
          <p><%= image_tag(basket_item.item.image_url, class: 'basket__img') %></p>
          <p><%= basket_item.item.title.capitalize %></p>
          <p><%= number_to_currency(basket_item.item.price) %></p>
          <%= link_to 'Удалить из корзины',basket_path(basket_item),
                               method: :delete,
                               data: { confirm: 'Вы уверены?' } %>
        </div>
      </div>
    <% end %>
    <div class="clearfix"></div>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :item_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description,rows:3, id: :item_description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :item_image_url %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :item_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>


<% @items.each do |item| %>
  <div class="entry">
    <div class="col-md-2 col-xs-12">
      <%= image_tag(item.image_url, class: 'item__image') %>
    </div>
    <div class="col-md-10 col-xs-12">
      <div class="entry__text">
        <p class="entry__text-title"><%= item.title.capitalize %></p>
        <p class="entry__text-description"><%= truncate(item.description) %></p>
        <p class="entry__text-price"><%= number_to_currency(item.price) %></p>
        <%= button_to "Добавить в корзину", add_item_path(item_id: item) %>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @item.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Attachment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller.controller_name %>">
    <div class="header">
      <%= link_to root_path do%>
        <%= image_tag("logo.png")%>
      <%end%>
      <h1 class="caption"><%=@page_title || "Книжный магазин"%></h1>
      <span><%=link_to "Корзина", basket_index_path, class: "header__basket"  %></span>
    </div>
    <div class="container">
      <% flash.each do |key, message| %>
        <p class="<%= key %>"><%= message %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>